radekholy24/tyntec-api-collection

sms/v1/openapi.yaml

These operations return 200, so 201 can be deleted I guess.

Remove response 201 from /messaging/v1/sms

---

conversations/v3/common.yaml

Fix link to Webhook Events in common conversations operations

---

conversations/v3/common.yaml

**Should be discussed what should be documented.**

Document at least what I know about MessageDeliveryEvents

---

conversations/v3/telegram.yaml
conversations/v3/viber.yaml
conversations/v3/wechat.yaml

Fix rendering types of messages in the bulk message requests in Conversations API

---

conversations/v3/webhook-events-v2.yaml
conversations/v3/webhook-events-v3.yaml

Replace tyntec application with Configuration in Webhook Events

---

conversations/v3/whatsapp.yaml

Both examples and the implementation returns a number.

Make facebookBusinessManagerId a number

---

conversations/v3/whatsapp.yaml

**Should be discussed whether this is the correct fix**

Make example of phoneNumber in WhatsAppPhoneNumber a string

---

conversations/v3/telegram.yaml

Fix examples of Telegram messages

---

conversations/v3/webhook-events-v2.yaml
conversations/v3/webhook-events-v3.yaml

Make example of from and to in MessageStatusDeletedEvent strings

---

conversations/v3/webhook-events-v2.yaml
conversations/v3/webhook-events-v3.yaml

Make examples of from and to in APIEvent strings

---

conversations/v3/configurations.yaml

Make example of phoneNumber in SMSChannelResponse a string

---

conversations/v3/configurations.yaml

Make example of weChatId in WeChatChannelResponse a string

---

conversations/v3/configurations.yaml

Make example of appId in WeChatChannelResponse a string

---

third-party/eazy/v1/openapi.yaml

Add version to https://api.cmd.tyntec.com/v3

---

sms/v1/openapi.yaml

Accidentally merged https://github.com/yet-another-radek/tyntec-api-collection/pull/6. Opening again.

Set the schema of error responses in SMS API

---

portability-check/v1/openapi.yaml
sms/v1/openapi.yaml

Turn possible values of nrhTechnology in GnpResponse into an enum

---

portability-check/v1/openapi.yaml
sms/v1/openapi.yaml
third-party/eazy/v1/openapi.yaml

Change the type of overallPrice in RestMessagePart to number

---

sms/v1/openapi.yaml
third-party/eazy/v1/openapi.yaml

Fix the items of events in webhookResponse

---

portability-check/v1/openapi.yaml
sms/v1/openapi.yaml
third-party/eazy/v1/openapi.yaml

**Should be discussed whether this is a correct fix.**

Add ApiKeyHeader to all operations in SMS API

---

sms/v1/openapi.yaml
third-party/eazy/v1/openapi.yaml

**Should be discussed whether this is the proper fix.** Maybe it should be just an array of strings?

Fix the reference to labels items in conversationResponse

---

sms/v1/openapi.yaml
third-party/eazy/v1/openapi.yaml

Fix the type of id in response to POST https://api.cmd.tyntec.com/v3/channels/{channelJid}/messages/{contactJid}

---

portability-check/v1/openapi.yaml
sms/v1/openapi.yaml
third-party/eazy/v1/openapi.yaml

Make validity in SMS API a number

---

sms/v1/openapi.yaml
third-party/eazy/v1/openapi.yaml

Fix the items of objects in apiKeyResponse

---

sms/v1/openapi.yaml
third-party/eazy/v1/openapi.yaml

Fix the name of isPinned in POST https://api.cmd.tyntec.com/v3/channels/{channelJid}/contacts/{contactJid}/notes/{id}

---

portability-check/v1/openapi.yaml
sms/v1/openapi.yaml
third-party/eazy/v1/openapi.yaml

Change the type of originMCC in InboundMessage to number

---

portability-check/v1/openapi.yaml
sms/v1/openapi.yaml
third-party/eazy/v1/openapi.yaml

Make example of originTtId in InboundMessage a string

---

portability-check/v1/openapi.yaml
sms/v1/openapi.yaml
third-party/eazy/v1/openapi.yaml

Remove the wrapping array from the response to GET https://api.tyntec.com/byon/phonebook/v1/numbers

---

portability-check/v1/openapi.yaml
sms/v1/openapi.yaml
third-party/eazy/v1/openapi.yaml

Change the type of price in RestMessagePart to number

---

portability-check/v1/openapi.yaml
sms/v1/openapi.yaml
third-party/eazy/v1/openapi.yaml

Remove the wrapping array from the response to GET https://api.tyntec.com/byon/contacts/v1

---

portability-check/v1/openapi.yaml
sms/v1/openapi.yaml
third-party/eazy/v1/openapi.yaml

Make example of ttid in RestMessagePart a string

---

portability-check/v1/openapi.yaml
sms/v1/openapi.yaml
third-party/eazy/v1/openapi.yaml

Remove extra 2XX responses from SMS API

---

portability-check/v1/openapi.yaml
sms/v1/openapi.yaml
third-party/eazy/v1/openapi.yaml

Remove extra */* contents from responses in SMS API

---

portability-check/v1/openapi.yaml
sms/v1/openapi.yaml
third-party/eazy/v1/openapi.yaml

Change the type of originMNC in InboundMessage to number

---

portability-check/v1/openapi.yaml
sms/v1/openapi.yaml
third-party/eazy/v1/openapi.yaml

Change the scheme of the response to GET https://api.tyntec.com/byon/phonebook/v1/numbers/{phoneNumber} to PhoneProvisioningEntity

---

sms/v1/openapi.yaml
third-party/eazy/v1/openapi.yaml

Fix the documentation of message in POST https://api.cmd.tyntec.com/v3/channels/{channelJid}/messages/{contactJid}

---

sms/v1/openapi.yaml
third-party/eazy/v1/openapi.yaml

Document the body of PATCH https://api.cmd.tyntec.com/v3/channels/{channelJid}/automated-messages/{type}

---

sms/v1/openapi.yaml
third-party/eazy/v1/openapi.yaml

**Should be discussed what is the proper fix.**

Document items of names in contactResponse

---

third-party/eazy/v1/openapi.yaml

Note to me: don't merge it to `master`!

Fix grammar errors and typos in the descriptions of PATCH https://api.cmd.tyntec.com/v3/channels/{channelJid}/automated-messages/{type}

---

portability-check/v1/openapi.yaml
sms/v1/openapi.yaml

Turn possible values of mscTechnology in GnpResponse into an enum

---

portability-check/v1/openapi.yaml
sms/v1/openapi.yaml

Turn possible values of hlrTechnology in GnpResponse into an enum

---

portability-check/v1/openapi.yaml
sms/v1/openapi.yaml

Turn possible values of imsiTechnology in GnpResponse into an enum

---

portability-check/v1/openapi.yaml
sms/v1/openapi.yaml

Turn possible values of technology in GnpResponse into an enum

---

portability-check/v1/openapi.yaml
sms/v1/openapi.yaml

Make example of synchronous in GnvResponse a boolean

---

portability-check/v1/openapi.yaml
sms/v1/openapi.yaml

Make example of synchronous in GnpResponse a boolean

---

portability-check/v1/openapi.yaml
sms/v1/openapi.yaml

Make example of price in GnpResponse a number

---

portability-check/v1/openapi.yaml
sms/v1/openapi.yaml

Fix description of "ported" values in GnpResponse

---

verification/v0/phoneVerification.yaml

Make the boolean properties of numberResponse boolean

---

verification/v0/phoneVerification.yaml

**Should be discussed whether this is correct.**

Remove the extra apiKey header from GET /health

---

portability-check/v1/openapi.yaml
third-party/eazy/v1/openapi.yaml

Fix grammar errors and typos in the descriptions of assistantResponse

---

portability-check/v1/openapi.yaml
third-party/eazy/v1/openapi.yaml

Fix grammar errors and typos in the descriptions of autoMessageResponse

---

conversations/v3/intro.yaml

**Should be discussed whether this is better wording...**

Improve the wording of the Link headers section in Conversations API
